version: '3.7'
services:
  trino:
    hostname: trino.tvr.local
    image: 'trinodb/trino:351'
    ports:
      - '8086:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
    networks:
      - trino-network
  minio:
    hostname: minio.tvr.local
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - trino-network

volumes:
  minio-data:
    external: true
#    driver: local
  hive-data:
    external: true
  mysql_data_dir:
    external: true

networks:
  trino-network:
    external: true
