version: '3.7'
services:
  trino:
    hostname: trino.my.local
    image: 'trinodb/trino:453'
    ports:
      - '8086:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
      - ./trino/etc:/etc/trino:ro
    networks:
      - trino-network
    environment:
      HTTPS_PROXY: ""
      HTTP_PROXY: ""
      https_proxy: ""
      http_proxy: ""
    deploy:
      resources:
        reservations:
          cpus: 2.0
          memory: 2048M
  minio:
    hostname: minio.my.local
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
      HTTPS_PROXY: ""
      HTTP_PROXY: ""
      https_proxy: ""
      http_proxy: ""
    command: server /data --console-address ":9001"
    networks:
      - trino-network
    deploy:
      resources:
        reservations:
          cpus: 1.0
          memory: 2048M

volumes:
  minio-data:
    external: true
  #    driver: local
  hive-data:
    external: true
  mysql_data_dir:
    external: true

networks:
  trino-network:
    external: true
